name: Sync Fork with Upstream

on:
  schedule:
    # Runs at the beginning of every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow.

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags.

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "guy.duer@firebolt.io"

    - name: Add remote upstream
      run: git remote add upstream https://github.com/firebolt-db/godocs.git

    - name: Fetch changes from upstream
      run: git fetch upstream

    - name: Merge changes from upstream/main to main
      run: |
        git checkout main
        git merge upstream/main
        git push origin main
